### ISSUE TITLE
[DOCUMENTATION] Actualizar archivo README

### ISSUE THREAD

**Issue by Brayan-Ric** [Brubrux/Proyecto-AnInfo-#10]
## 📚 Documentation

Actualizar el README para que incluya:

- Instrucciones de instalación y ejecución del juego
- Instrucciones del juego (cómo funciona, cuales son los niveles de dificultad, como afectan a la jugabilidad, etc.)

**Comment by Brubrux** [comment]
modificar para que no sea una user story

**Comment by jfgulden** [comment]
## 📚 Documentation



Actualizar el README para que incluya:

- Instrucciones de instalación y ejecución del juego
- Instrucciones del juego (cómo funciona, )
