### ISSUE TITLE
[FEATURE] Seleccionar nivel de dificultad

### ISSUE THREAD

**Issue by AlanValdevenito** [Brubrux/Proyecto-AnInfo-#11]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es que el usuario tenga la opción de elegir con que dificultad jugar una partida. 

### Motivation

Esta característica debería implementarse en el proyecto ya que permite que los usuarios adapten su experiencia. Es decir, esto nos permitira tener usuarios inexpertos y también expertos. Además, esta característica hace el juego más desafiante.

### Implementation

- Las dificultades posibles son: FACIL, MEDIO, DIFICIL.
- La dificultad por default es NORMAL, pero puede cambiarse antes de comenzar la partida (ver issue #27 ). 
- La dificultad afecta el número de intentos. 
  - En la dificultad FACIL el usuario tendrá 7 intentos.
  - En la dificultad NORMAL el usuario tendrá 5 intentos
  - En la dificultad DIFICIL el usuario tendrá 3 intentos.
- La dificultad afecta el largo de la palabra y la complejidad de esta.
- La dificultad se ellige desde la opcion "Dificultad" en la pantalla de inicio

**Comment by Brubrux** [comment]
tambien agregar dificultad de palabra

**Comment by Brubrux** [comment]
debe quedar explicito, cuando se setea la dificultad? 
Propuesta: dificultad basada en largo de palabra

**Comment by iinaki** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que el usuario tenga la opción de elegir con que dificultad jugar una partida. 

### Motivation



Esta característica debería implementarse en el proyecto ya que permite que los usuarios adapten su experiencia. Es decir, esto nos permitira tener usuarios inexpertos y también expertos. Además, esta característica hace el juego más desafiante.

### Implementation



- Las dificultades posibles son: FACIL, MEDIO, DIFICIL.
- La dificultad debe elegirse antes de comenzar una partida. 
- La dificultad afecta el número de intentos.
- La dificultad afecta el largo de la palabra y la complejidad de esta.
- Al seleccionar la dificultad, en la interfaz grafica se utilizarían botones que tengan escrita la palabra de la dificultad. El usuario que esta interactuando debe poder apretar uno de estos botones.
