### ISSUE TITLE
[RESEARCH] Buscar y armar una base con todas las palabras que va a contener el juego

### ISSUE THREAD

**Issue by Brubrux** [Brubrux/Proyecto-AnInfo-#13]
Como developer
quiero tener la lista de palabras y oraciones que van a ser usadas en el juego
para poder elegir una al azar

**Comment by Brubrux** [comment]
charlar sobre cambiarlo por una biblioteca que tire palabra random

**Comment by iinaki** [comment]
esta issue yo la cerraria me parece
