### ISSUE TITLE
[FEATURE] Soporte para frases y palabras

### ISSUE THREAD

**Issue by Brubrux** [Brubrux/Proyecto-AnInfo-#15]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es que al usuario le aparezcan tanto palabras como frases separadas por espacios.

### Motivation

Esta característica debería implementarse en el proyecto para que el juego sea más desafiante para el usuario.

### Implementation

- El juego debe distinguir entre letras y espacios. Al inicio del juego, cuando se pasa la palabra a la lista de letras a adivinar, se dejan afuera los espacios.

- La interfaz grafica debe mostrar tanto letras como espacios en blanco. Al printear la palabra por pantalla, si se encuentra un espacio, este se muestra.

- El espacio que separe las palabras no puede ser adivinable.

**Comment by iinaki** [comment]
Esta abría que pensar que implica que se puedan tener frases y palabras:
- cuando se muestra la frase los espacios en blanco no pueden ser una letra adivinable, osea que te muestre que es espacio en blanco
- no se puede adivinar un espacio

**Comment by AlanValdevenito** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que al usuario le aparezcan tanto palabras como frases separadas por espacios.

### Motivation



Esta característica debería implementarse en el proyecto para que el juego sea más desafiante para el usuario.

### Implementation



El juego debe distinguir entre letras y espacios .

La interfaz grafica debe mostrar tanto letras como espacios en blanco.

El espacio que separe las palabras no puede ser adivinable.

### Additional context
Add any other context or screenshots about the feature request here.
