### ISSUE TITLE
[FEATURE] Guardar letras ya mencionadas por el jugador

### ISSUE THREAD

**Issue by Brubrux** [Brubrux/Proyecto-AnInfo-#3]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es que se le muestre al jugador las letras que ya han sido adivinadas o mencionadas en intentos anteriores para evitar repeticiones.

### Motivation

Esta característica debería implementarse en el proyecto porque evita repeticiones innecesarias. Además proporciona una experiencia de juego más fluida ya que el usuario no tendría que estar memorizando o intentando recordar que letras ya intento.

### Implementation

Llevar un registro de las letras que el jugador ha adivinado o mencionado anteriormente. Este registro se llevaría en un vector que guarde las letras que hay que adivinar con la palabra que haya tocado, por ejemplo si la palabra es "agarrar", el vector que se forma es [a, g, r]. Con eso tendríamos la info de lo que el jugador necesita adivinar. Después podemos tener otro vector que guarde las letras adivinadas, que empezaría vacio y se iría completando a medida que juege al juego.

Mostrar estas letras en una parte de la interfaz del juego de forma que sean claramente visibles y distinguibles para el usuario. 

### Criterios de Aceptacion

- Tenemos dos vectores que guardan las letras
- Si hay una palabra en donde se repiten letras, se guarda en el vector una sola vez la letra repetida

**Comment by AlanValdevenito** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que se le muestre al jugador las letras que ya han sido adivinadas o mencionadas en intentos anteriores para evitar repeticiones.

### Motivation



Esta característica debería implementarse en el proyecto porque evita repeticiones innecesarias. Además proporciona una experiencia de juego más fluida ya que el usuario no tendría que estar memorizando o intentando recordar que letras ya intento.

### Implementation



Llevar un registro de las letras que el jugador ha adivinado o mencionado anteriormente. Este registro se llevaría en un diccionario de la forma (clave, valor) = (letra, cantidad).

Mostrar estas letras en una parte de la interfaz del juego de forma que sean claramente visibles y distinguibles para el usuario.

### Additional context
Add any other context or screenshots about the feature request here.

**Comment by iinaki** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que se le muestre al jugador las letras que ya han sido adivinadas o mencionadas en intentos anteriores para evitar repeticiones.

### Motivation



Esta característica debería implementarse en el proyecto porque evita repeticiones innecesarias. Además proporciona una experiencia de juego más fluida ya que el usuario no tendría que estar memorizando o intentando recordar que letras ya intento.

### Implementation



Llevar un registro de las letras que el jugador ha adivinado o mencionado anteriormente. Este registro se llevaría en un vector que guarde las letras que hay que adivinar con la palabra que haya tocado, por ejemplo si la palabra es "agarrar", el vector que se forma es [a, g, r]. Con eso tendríamos la info de lo que el jugador necesita adivinar. Después podemos tener otro vector que guarde las letras adivinadas, que empezaría vacio y se iría completando a medida que juege al juego.

Mostrar estas letras en una parte de la interfaz del juego de forma que sean claramente visibles y distinguibles para el usuario. 

### Criterios de Aceptacion

- Tenemos dos vectores que guardan las letras
- Si hay una palabra en donde se repiten letras, se guarda en el vector una sola vez la letra repetida
