### ISSUE TITLE
[FEATURE] Actualizar el estado del ahorcado frente a intentos fallidos

### ISSUE THREAD

**Issue by AlanValdevenito** [Brubrux/Proyecto-AnInfo-#4]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es actualizar el estado visual del ahorcado en función de la cantidad de intentos fallidos realizados por el usuario.

### Motivation

Esta característica debería implementarse en el proyecto ya que proporciona una representación gráfica del progreso del usuario. Ayuda al usuario a comprender cuántos intentos le quedan y agrega un elemento visual al juego.

### Implementation

Representación visual en la interfaz grafica. La representación visual debe reflejar con precisión el progreso del usuario, desde un ahorcado inicial "incompleto" hasta un ahorcado "completo" a medida que el usuario tiene intentos fallidos.

Contador con la cantidad de intentos totales. A medida que el usuario falle, el contador ira disminuyendo y se ira actualizando la representación visual en base al valor de este contador.

### Criterios de Aceptacion

- se tiene un contador con la cantidad de intentos fallidos que lleva el jugador
- el contador se actualiza cuando el jugador elije una letra que esta mal
- el contador se compara con el Nivel de Dificultad, si esta en facil puede tirar a pegar 7 veces, medio tiene 5, y en dificil tiene 3
- si el jugador falla más de lo que se puede, el juego termina
- Se muestra y se actualiza el personaje del ahorcado (va a tener que ser una issue nueva)

**Comment by iinaki** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es actualizar el estado visual del ahorcado en función de la cantidad de intentos fallidos realizados por el usuario.

### Motivation



Esta característica debería implementarse en el proyecto ya que proporciona una representación gráfica del progreso del usuario. Ayuda al usuario a comprender cuántos intentos le quedan y agrega un elemento visual al juego.

### Implementation



Representación visual en la interfaz grafica. La representación visual debe reflejar con precisión el progreso del usuario, desde un ahorcado inicial "completo" hasta un ahorcado "incompleto" a medida que el usuario tiene intentos fallidos.

Contador con la cantidad de intentos totales. A medida que el usuario falle, el contador ira disminuyendo y se ira actualizando la representación visual en base al valor de este contador.

### Criterios de Aceptacion

- se tiene un contador con la cantidad de intentos fallidos que lleva el jugador
- el contador se actualiza cuando el jugador elije una letra que esta mal
- el contador se compara con el Nivel de Dificultad, si esta en facil puede tirar a pegar 7 veces, medio tiene 5, y en dificil tiene 3
- si el jugador falla más de lo que se puede, el juego termina
