### ISSUE TITLE
[FEATURE] Colocar letra correcta en espacio pertinente

### ISSUE THREAD

**Issue by Brubrux** [Brubrux/Proyecto-AnInfo-#5]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es que cuando el jugador adivine una letra correctamente, que la letra se coloque en los espacios correspondientes de la palabra que se está adivinando.

### Motivation

Esta característica debería implementarse en el proyecto porque es esencial para proporcionar retroalimentación visual al jugador. 

### Implementation

Al principio del juego la palabra empieza toda oculta, con guiones "_" . Despues cuando el jugador va jugando, la palabra se printea comparandola con el vector de letras adivinadas. Por cada letra de la palabra se recorre el vector de letras que se adivinaron, y si esta letra está en el vector se va a mostrar, y sino no.
Por ejemplo:
palabra: agarrar

1) PRINT: _______  LETRAS A ADIVINAR: [a,g,r]    LETRAS ADIVINADAS: [ ]
2) PRINT: a_a__a_ LETRAS A ADIVINAR: [g,r]   LETRAS ADIVINADAS: [ a ]

- Detectar si la letra adivinada por el jugador es parte de la palabra objetivo.
- Si la letra adivinada es correcta y se encuentra en la palabra objetivo, colocarla en todos los espacios donde debería aparecer.
- Actualizar la representación visual de la palabra en función de las letras adivinadas correctamente.

**Comment by AlanValdevenito** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que cuando el jugador adivine una letra correctamente, asegúrate de que la letra se coloque en los espacios correspondientes de la palabra que se está adivinando.

### Motivation



Esta característica debería implementarse en el proyecto porque es esencial para proporcionar retroalimentación visual al jugador. 

### Implementation



Detectar si la letra adivinada por el jugador es parte de la palabra objetivo.

Si la letra adivinada es correcta y se encuentra en la palabra objetivo, colocarla en todos los espacios donde debería aparecer.

Actualizar la representación visual de la palabra en función de las letras adivinadas correctamente.

### Additional context
Add any other context or screenshots about the feature request here.

**Comment by iinaki** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que cuando el jugador adivine una letra correctamente, que la letra se coloque en los espacios correspondientes de la palabra que se está adivinando.

### Motivation



Esta característica debería implementarse en el proyecto porque es esencial para proporcionar retroalimentación visual al jugador. 

### Implementation



Al principio del juego la palabra empieza toda oculta, con guiones "_" . Despues cuando el jugador va jugando, la palabra se printea comparandola con el vector de letras adivinadas. Por cada letra de la palabra se recorre el vector de letras que se adivinaron, y si esta letra está en el vector se va a mostrar, y sino no.
Por ejemplo:
palabra: agarrar

1) PRINT: _______  LETRAS A ADIVINAR: [a,g,r]    LETRAS ADIVINADAS: [ ]
2) PRINT: a_a__a_ LETRAS A ADIVINAR: [g,r]   LETRAS ADIVINADAS: [ a ]

- Detectar si la letra adivinada por el jugador es parte de la palabra objetivo.
- Si la letra adivinada es correcta y se encuentra en la palabra objetivo, colocarla en todos los espacios donde debería aparecer.
- Actualizar la representación visual de la palabra en función de las letras adivinadas correctamente.
