### ISSUE TITLE
[FEATURE] Menú principal (Interfaz del juego)

### ISSUE THREAD

**Issue by Brayan-Ric** [Brubrux/Proyecto-AnInfo-#6]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es que cuando el juego se inicie, mostrar un mensaje de bienvenida al jugador. La pantalla de bienvenida se mostrará al inicio del juego.

### Motivation

Esta característica debería implementarse en el proyecto para brindar una mejor UX.

### Implementation

- Se debe mostrar un menú con las opciones que ofrece el juego:
1. Una opción de "Empezar" para que el jugador comience el juego desde la pantalla de bienvenida.
2. Una opción de "Dificultad" para preguntar al jugador la dificultad en la que quiere jugar, explicando que cambia en cada dificultad. Si no cambia de dificultad, se juega con la default que es "Normal"
3. Una opción de "Reglas", que muestre las instrucciones del juego
4. Una opción de "Salir" para terminar el juego

- El menú de inicio se queda esperando por uno de los números anteriores ( 1. Empezar, 2. Dificultad, y así )
- Cuando el jugador ingresa el 1 inicia el juego
- Cuando el jugador ingresa el 2 se muestra un menu para elegir la dificultad
- Cuando el jugador ingresa el 3 se muestran las reglas del juego
- Cuando el jugador ingresa el 4 se termina el juego
A su vez, se debe mostrar un cartel en el margen superior derecho que indique cual es la dificultad actual, de la siguiente forma: 'DIFICULTAD: [NIVEL]'

**Comment by jfgulden** [comment]
Como usuario quiero que cuando se inicie el juego me de la bienvenida para tener una mejor UX

**Comment by AlanValdevenito** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que cuando el juego se inicie, mostrar un mensaje de bienvenida al jugador.

### Motivation



Esta característica debería implementarse en el proyecto para brindar una mejor UX.

### Implementation



La pantalla de bienvenida se mostrará al inicio del juego.

Se debe proporcionar una opción para que el jugador comience el juego desde la pantalla de bienvenida.

### Additional context
Add any other context or screenshots about the feature request here.

**Comment by iinaki** [comment]
## 🚀 Feature



La característica que nos gustaría que se vea en el proyecto es que cuando el juego se inicie, mostrar un mensaje de bienvenida al jugador.

### Motivation



Esta característica debería implementarse en el proyecto para brindar una mejor UX.

### Implementation



La pantalla de bienvenida se mostrará al inicio del juego.

- Se debe proporcionar una opción para que el jugador comience el juego desde la pantalla de bienvenida.
- Se debe preguntar al jugador la dificultad en la que quiere jugar, explicando que cambia en cada dificultad
