### ISSUE TITLE
[FEATURE] Mensajes para informar el estado del juego

### ISSUE THREAD

**Issue by AlanValdevenito** [Brubrux/Proyecto-AnInfo-#7]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es mostrar al usuario mensajes para informar sobre el estado de la partida (cantidad de letras adivinadas correctas, cantidad de letras adivinadas incorrectas, cantidad de intentos restantes, etc).

### Implementation

Se lleva el estado del juego en las listas de letras por adivinar, y letras adivinadas. En cada jugada, según el input del usuario, el estado del juego cambia, y con este se muestran por pantalla unos mensajes para guiar el juego.

Los mensajes deben ser claros y descriptivos. 
- Un "BIEN!" cuando se adivina una letra, y un "MAL AHI" cuando se elige mal.
- "Intentos restantes: X".
- "Pistas restantes: X".
- Letras adivinadas
- Personaje del ahorcado

**Comment by iinaki** [comment]
en la parte de motivacion pondría solamente lo de proporcionar feedback

**Comment by jfgulden** [comment]
Implementation: en lugar de llevar contador, sería preferible guardar en un vector las letras que hay que adivinar, y por cada letra que se adivina, quitarla de ese vector y guardarla en un vector de letras adivinadas.

**Comment by iinaki** [comment]
## 🚀 Feature

La característica que nos gustaría que se vea en el proyecto es mostrar al usuario mensajes para informar sobre el estado de la partida (cantidad de letras adivinadas correctas, cantidad de letras adivinadas incorrectas, cantidad de intentos restantes, etc).


### Implementation

Se lleva el estado del juego en las listas de letras por adivinar, y letras adivinadas. En cada jugada, según el input del usuario, el estado del juego cambia, y con este se muestran por pantalla unos mensajes para guiar el juego.

Los mensajes deben ser claros y descriptivos. 
- Un "BIEN!" cuando se adivina una letra, y un "MAL AHI" cuando se elige mal.
- "Intentos restantes: X".
- "Pistas restantes: X".
- Letras adivinadas
- Personaje del ahorcado
